import os
import openai
import requests
import time
from github import Github
from flask import Flask, request, jsonify

app = Flask(__name__)

# This should be loaded from a secure location
SHARED_SECRET = os.environ.get("SHARED_SECRET", "default_secret")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
LLM_API_KEY = os.environ.get("LLM_API_KEY")

openai.api_key = LLM_API_KEY


import base64

def generate_app(brief, attachments):
    """
    Generates application code using an LLM.
    """
    prompt = f"Create a single self-contained HTML file that implements the following brief: {brief}."

    if attachments:
        prompt += "\n\nThe following attachments are provided:\n"
        for attachment in attachments:
            name = attachment.get('name')
            url = attachment.get('url')
            if name and url:
                # Assuming data URI format: data:[<mediatype>][;base64],<data>
                header, encoded_data = url.split(',', 1)
                decoded_data = base64.b64decode(encoded_data).decode('utf-8')
                prompt += f"\n- {name}:\n```\n{decoded_data}\n```"

    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a web developer that creates single-file HTML applications."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error generating app: {e}")
        return None


def deploy_to_github(task_id, generated_code, brief):
    """
    Deploys the generated code to a new GitHub repository.
    """
    g = Github(GITHUB_TOKEN)
    user = g.get_user()
    repo_name = task_id

    try:
        repo = user.get_repo(repo_name)
        # If the repo exists, we might want to update it. For now, let's just delete and recreate for simplicity in round 1.
        # In a real scenario, we would update the existing repo.
        repo.delete()
        repo = user.create_repo(repo_name, private=False, auto_init=False)
    except Exception:
        repo = user.create_repo(repo_name, private=False, auto_init=False)

    # Add MIT License
    mit_license = """
MIT License

Copyright (c) 2024 Your Name

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
    repo.create_file("LICENSE", "Add MIT License", mit_license)

    # Add README.md
    readme_content = f"""
# {repo_name}

This project was automatically generated based on the following brief:

> {brief}

## Setup

No setup is required. This is a single-page static application.

## Usage

Open the GitHub Pages URL to view the application.

## Code Explanation

The application is a single HTML file generated by an LLM.

## License

This project is licensed under the MIT License.
"""
    repo.create_file("README.md", "Add README.md", readme_content)

    # Add the generated code
    commit = repo.create_file("index.html", "Add generated application code", generated_code)
    commit_sha = commit['commit'].sha

    # Enable GitHub Pages
    repo.edit(has_pages=True, homepage=f"https://{user.login}.github.io/{repo_name}/")

    pages_url = f"https://{user.login}.github.io/{repo_name}/"
    repo_url = repo.html_url

    return repo_url, commit_sha, pages_url


def notify_evaluation_service(evaluation_url, email, task, round_num, nonce, repo_url, commit_sha, pages_url):
    """
    Notifies the evaluation service of the deployment.
    """
    payload = {
        "email": email,
        "task": task,
        "round": round_num,
        "nonce": nonce,
        "repo_url": repo_url,
        "commit_sha": commit_sha,
        "pages_url": pages_url,
    }

    retries = [1, 2, 4, 8]
    for delay in retries:
        try:
            response = requests.post(evaluation_url, json=payload, headers={'Content-Type': 'application/json'})
            if response.status_code == 200:
                print("Successfully notified evaluation service.")
                return True
            else:
                print(f"Failed to notify evaluation service. Status code: {response.status_code}. Retrying in {delay}s...")
        except requests.exceptions.RequestException as e:
            print(f"An error occurred: {e}. Retrying in {delay}s...")

        time.sleep(delay)

    print("Failed to notify evaluation service after all retries.")
    return False


@app.route('/api-endpoint', methods=['POST'])
def handle_request():
    data = request.get_json()

    if not data or 'secret' not in data or data['secret'] != SHARED_SECRET:
        return jsonify({"error": "Unauthorized"}), 401

    # Extract all required fields from the request
    email = data.get('email')
    task_id = data.get('task')
    round_num = data.get('round')
    nonce = data.get('nonce')
    brief = data.get('brief')
    evaluation_url = data.get('evaluation_url')
    attachments = data.get('attachments')

    required_fields = [email, task_id, round_num, nonce, brief, evaluation_url]
    if not all(required_fields):
        return jsonify({"error": "One or more required fields are missing"}), 400

    generated_code = generate_app(brief, attachments)
    if not generated_code:
        return jsonify({"error": "Failed to generate application code"}), 500

    repo_url, commit_sha, pages_url = deploy_to_github(task_id, generated_code, brief)
    if not repo_url:
        return jsonify({"error": "Failed to deploy to GitHub"}), 500

    notification_success = notify_evaluation_service(
        evaluation_url, email, task_id, round_num, nonce, repo_url, commit_sha, pages_url
    )

    if not notification_success:
        return jsonify({"error": "Failed to notify evaluation service"}), 500

    return jsonify({
        "status": "success",
        "message": "Application deployed and evaluation service notified successfully."
    }), 200


if __name__ == '__main__':
    app.run(debug=True)